### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bbenoit** [adistoe/EnvLoader#1]
Hello.
Nice small tool, very useful and easy.
But I **cannot** use it as there is no associated license (thus **it is "proprietary"** by default). Too bad.

Would you mind, if you are the original author, put your work under an open source license ?

I would suggest a permissive license like _MIT_ or _New BSD_.

Thanks in advance.

**Comment by adistoe** [comment]
Hello bbenoit

Thank you for your interest in this tool.
I just added an MIT license file.

Happy coding
